### ISSUE TITLE
TranslateStack を作成

### ISSUE THREAD

**Issue by matsuihidetoshi** [jaws-ug/jpk2024-broadcast-backend#2]
# 概要
OBS Studion LocalVocal プラグインから送られてきた文字起こしテキストを受け取って、まずは一旦 DynamoDB に raw data として putItem する。
その後、同じ文字列を Amazon Translate で翻訳する。
翻訳結果は DynamoDB に対して putItem したいが、そのテーブルは https://github.com/jaws-ug/jpk2024-broadcast-viewer 側で Amplify 管理下で作成する想定なので、一旦は翻訳結果をログ出力なり HTTP レスポンスするなりで良い。

# 参考
- API Gateway + Lambda + Translate で翻訳する部分は、 [これ](https://github.com/matsuihidetoshi/translate-function) でほとんど網羅できるはず。

# タスク
- [ ] TranslateStack を作成（以下、その内部の実装）
- [ ] API Gateway 作成
- [ ] Lambda 関数コード作成
- [ ] Lambda 関数作成
- [ ] API Gateway + Lambda の繋ぎこみ
- [ ] raw data 用 DynamoDB 作成
- [ ] raw data を Lambda -> DynamoDB 書き込みする処理を追加
- [ ] Translate で翻訳する処理を追加
- [ ] 翻訳結果用 DynamoDB 作成
- [ ] 翻訳結果を Lambda -> DynamoDB 書き込みする処理を追加

**Comment by soda1p2** [comment]
Issue1に続けてこちら対応します！
